version: "3.9"

services:
  mysql-db:
    image: mysql:8.1
    container_name: chat_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chat_real
      MYSQL_USER: jairo
      MYSQL_PASSWORD: jairo123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
